# Site settings
title: Geneva Azure & PowerShell user group
description: Articles, meetups et conférences
url: "http://gapsug.ch/"

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL
# twitter_username: mateussousam # Twitter username

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
